services:
  webapp_local:
    container_name: webapp_local
    build:
      context: .
      dockerfile: app.Dockerfile
    image: webapp_local:version_4.2.1
    ports:
      - "8081:8001"
    env_file:
      - "D:\\Work\\git\\od_internal.env"
    restart: unless-stopped
