services:
  webapp_80:
    container_name: webapp_80
    build:
      context: .
      dockerfile: app.Dockerfile
    image: webapp_dev:version_3.9.2
    ports:
      - "8080:8001"
    env_file:
      - /home/shashank_daaslabs/Software/ec2_common.env
    restart: unless-stopped
    environment:
      - POSTGRES_SCHEMA=ec2_dev
    volumes:
      - /home/shashank_daaslabs/OD_DB_Files:/mnt/data
      - /home/shashank_daaslabs/Software/ec2_common.env:/mnt/env/ec2_common.env

  webapp_81:
    container_name: webapp_81
    build:
      context: .
      dockerfile: app.Dockerfile
    image: webapp_test:version_3.9.2
    ports:
      - "8081:8001"
    env_file:
      - /home/shashank_daaslabs/Software/ec2_common.env
    restart: unless-stopped
    environment:
      - POSTGRES_SCHEMA=ec2_stage
    volumes:
      - /home/shashank_daaslabs/OD_DB_Files:/mnt/data
      - /home/shashank_daaslabs/Software/ec2_common.env:/mnt/env/ec2_common.env
  
  webapp_82:
    container_name: webapp_82
    build:
      context: .
      dockerfile: app.Dockerfile
    image: webapp_test:version_3.9.2
    ports:
      - "8082:8001"
    env_file:
      - /home/shashank_daaslabs/Software/ec2_common.env
    restart: unless-stopped
    environment:
      - POSTGRES_SCHEMA=ec2_prod
    volumes:
      - /home/shashank_daaslabs/OD_DB_Files:/mnt/data
      - /home/shashank_daaslabs/Software/ec2_common.env:/mnt/env/ec2_common.env
