services:
  OD_INTERNAL:
    container_name: od_internal
    build:
      context: .
      dockerfile: app.Dockerfile
    image: webapp_internal:"${APP_VERSION}"
    ports:
      - "8081:8001"
    env_file:
      - "${ENV_FILE_OD_INT}"
    restart: unless-stopped
