services:
  webapp_stage:
    container_name: webapp_stage
    build:
      context: .
      dockerfile: app.Dockerfile
    image: webapp_test:version_3.9.2
    ports:
      - "8081:8001"
    env_file:
      - /home/shashank_daaslabs/Software/aws_stage.env
    restart: unless-stopped
    environment:
      - POSTGRES_SCHEMA=stage
    volumes:
      - /home/shashank_daaslabs/OD_DB_Files:/mnt/data
      - /home/shashank_daaslabs/Software/aws_stage.env:/mnt/env/aws_stage.env
  
  webapp_prod:
    container_name: webapp_prod
    build:
      context: .
      dockerfile: app.Dockerfile
    image: webapp_test:version_3.9.2
    ports:
      - "8081:8001"
    env_file:
      - /home/shashank_daaslabs/Software/aws_prod.env
    restart: unless-stopped
    environment:
      - POSTGRES_SCHEMA=prod
    volumes:
      - /home/shashank_daaslabs/OD_DB_Files:/mnt/data
      - /home/shashank_daaslabs/Software/aws_prod.env:/mnt/env/aws_prod.env
