services:
  webapp_80:
    container_name: webapp_80
    build:
      context: .
      dockerfile: app.Dockerfile
    image: webapp_dev:version_3.9.2
    ports:
      - "8080:8001"
    env_file:
      - /home/shashank_daaslabs/Software/webapp_ec2.env
    restart: unless-stopped
    environment:
      - POSTGRES_SCHEMA=dev_v3
      - DEPLOYMENT_TYPE="stage"
      - ADD_RV_TO_B2C=1
      - INCL_CAT_SCAT=1

  webapp_81:
    container_name: webapp_81
    build:
      context: .
      dockerfile: app.Dockerfile
    image: webapp_test:version_3.9.2
    ports:
      - "8081:8001"
    env_file:
      - /home/shashank_daaslabs/Software/webapp_ec2.env
    restart: unless-stopped
    environment:
      - POSTGRES_SCHEMA=dev_v3
      - DEPLOYMENT_TYPE="stage"
      - ADD_RV_TO_B2C=1
      - INCL_CAT_SCAT=1

  webapp_82:
    container_name: webapp_82
    build:
      context: .
      dockerfile: app.Dockerfile
    image: webapp_test:version_3.9.2
    ports:
      - "8082:8001"
    env_file:
      - /home/shashank_daaslabs/Software/webapp_ec2.env
    restart: unless-stopped
    environment:
      - POSTGRES_SCHEMA=dev_v3
      - DEPLOYMENT_TYPE="prod"
      - ADD_RV_TO_B2C=1
      - INCL_CAT_SCAT=0

networks:
  my_custom_network:
    name: OD_DB
    driver: bridge