services:
  webapp_stage:
    container_name: webapp_stage
    build:
      context: .
      dockerfile: app.Dockerfile
    image: webapp_test:version_3.9.2
    ports:
      - "8081:8001"
    env_file:
      - /home/shashank_daaslabs/Software/webapp_stage.env
    restart: unless-stopped
    environment:
      - POSTGRES_SCHEMA=stage
      - DEPLOYMENT_TYPE="stage"
      - ADD_RV_TO_B2C=1
      - INCL_CAT_SCAT=1
  
  webapp_prod:
    container_name: webapp_prod
    build:
      context: .
      dockerfile: app.Dockerfile
    image: webapp_test:version_3.9.2
    ports:
      - "8081:8001"
    env_file:
      - /home/shashank_daaslabs/Software/webapp_prod.env
    restart: unless-stopped
    environment:
      - POSTGRES_SCHEMA=prod
      - DEPLOYMENT_TYPE="prod"
      - ADD_RV_TO_B2C=1
      - INCL_CAT_SCAT=0

networks:
  my_custom_network:
    name: OD_DB
    driver: bridge