services:
  webapp_internal:
    container_name: webapp_internal
    build:
      context: .
      dockerfile: app.Dockerfile
    image: webapp_internal:version_4.2.1
    ports:
      - "8081:8001"
    env_file:
      - /home/shashank_daaslabs/Software/od_internal.env
    restart: unless-stopped
    environment:
      - ENV_FILE_PATH=/home/shashank_daaslabs/Software/od_internal.env

