# deployment
# webserver deployment yaml with envs
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ondc-open-data
  name: open-data-webserver-stage-deployment
  labels:
    app: open-data-webserver-stage
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: open-data-webserver-stage
  template:
    metadata:
      labels:
        app: open-data-webserver-stage
    spec:
      containers:
        - name: open-data-webserver-stage
          image: 568130295144.dkr.ecr.ap-south-1.amazonaws.com/ondc-open-data-web-app:webserverv2f484b3
          ports:
            - containerPort: 8001
          env:
            - name: POSTGRES_HOST
              value: "ondc-prod-prod-open-data-db.cuvt1j5xqeya.ap-south-1.rds.amazonaws.com"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "ondc-open-data-webapp-staging-user"
            - name: DB_HOST
              value: "ondc-prod-prod-open-data-db.cuvt1j5xqeya.ap-south-1.rds.amazonaws.com"
            - name: POSTGRES_DB
              value: "open_data_stage"
            - name: POSTGRES_SCHEMA
              value: "stage"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ondc-open-data-webapp-stage-secret
                  key: db_password
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ondc-open-data-webapp-secret-email
                  key: EMAIL_PASSWORD
            - name: CACHE_EXPIRY
              value: "108600"
            - name: LANDING_PAGE_ECHART_TABLE
              value: "landing_page_echart"
            - name: LANDING_PAGE_ECHART_CONFIG
              value: '{"config": { "domainConfig": { "domains": [ "Retail", "Mobility", "Logistics", "ONDC Network - All Domains" ], "colorLight": [ "#f9ceff", "#E3FBE8", "#fff3d7", "#FFF1E4" ], "colorDark": [ "#e76cf7", "#91cc75", "#fac858", "#ee6666" ] }, "chartTitle": "Monthly Network Orders" }}'
            - name: LOGISTIC_SEARCH_PINCODE_TBL
              value: "logistic_search_pincode"
            - name: ACTIVE_TOTAL_SELLERS_TABLE
              value: "active_total_sellers_cat_scat"
            - name: MONTHLY_DISTRICT_TBL
              value: "district_wise_monthly_aggregates_orders"
            - name: CAT_MONTHLY_DISTRICT_TBL
              value: "cat_district_wise_monthly_aggregates"
            - name: SUB_CAT_MONTHLY_DISTRICT_TBL
              value: "sub_cat_district_wise_monthly_aggregates"
            - name: SUB_CATEGORY_PENETRATION_TABLE
              value: "sub_category_penetration_orders"
            - name: LOGISTICS_MONTHLY_PROVIDERS_TBL
              value: "logistics_monthly_providers"
            - name: LOGISTIC_SEARCH_PINCODE_TBL
              value: "logistic_search_pincode"
            - name: DIM_CATEGORIES_TBL
              value: "dim_categories"
            - name: DIM_DISTRICTS_TBL
              value: "dim_districts"
            - name: TBL_PINCODE
              value: "pincode"
            - name: LANDING_PAGE_ECHART_TABLE
              value: "landing_page_echart"
            - name: MONTHLY_PROVIDERS_TBL
              value: "monthly_providers"
            - name: CORS_ALLOWED_ORIGINS
              value: "http://localhost:4200,http://localhost:8001,http://localhost:8081,http://172.31.41.128:8081,http://15.206.0.116:8081"
            - name: DATA_UPLOAD_MAX_MEMORY_SIZE
              value: "20485760"
            - name: DEBUG
              value: "1"
            - name: VER_MAJOR
              value: "4"
            - name: VER_MINOR
              value: "2"
            - name: VER_MINOR_MINOR
              value: "1"
            - name: START_DATE
              value: "2024-04-01"
            - name: APP_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret-key
                  key: app_secret_key
          resources:
            requests:
              memory: "500Mi"
              cpu: "250m"
            limits:
              memory: "500Mi"
              cpu: "250m"

---
# webserver service yaml
apiVersion: v1
kind: Service
metadata:
  name: open-data-webserver-service-staging
  namespace: ondc-open-data
spec:
  selector:
    app: open-data-webserver-stage
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: NodePort

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: open-data-webserver-staging-hpa
  namespace: ondc-open-data
spec:
  maxReplicas: 1
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: open-data-webserver-stage-deployment
  targetCPUUtilizationPercentage: 80
