"""
Django settings for scikiq project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import importlib
from django_setup.setting_utils import get_env_value
DEPLOYMENT_TYPE = get_env_value('DEPLOYMENT_TYPE', True, 'default').lower()
print(DEPLOYMENT_TYPE)
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
print(BASE_DIR)
ENV_PATH = f"django_setup.env_type.{DEPLOYMENT_TYPE}"
# equiv. of your `import matplotlib.text as text`
env_mod_setting = importlib.import_module(f'{ENV_PATH}.setting')


ALLOWED_HOSTS = ['*']
CORS_ORIGIN_ALLOW_ALL = True
X_FRAME_OPTIONS = '*'
CORS_ALLOW_HEADERS = ['*']
DATA_UPLOAD_MAX_MEMORY_SIZE = 10242880 * 2


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '80u)c!qgeg+^sfbdi&i$&ii+w8#hcjaqq%ln(m7&fy&dvc%s@5'

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = False
if get_env_value('DEBUG') == "True":
    DEBUG = True
else:
    DEBUG = False

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
]+env_mod_setting.INSTALL_APP

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.BrokenLinkEmailsMiddleware',
]

CACHE_MIDDLEWARE_SECONDS = 60

ROOT_URLCONF = 'django_setup.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',

            ],
        },
    },
]

WSGI_APPLICATION = 'django_setup.wsgi.application'

DATABASES = env_mod_setting.DATABASES

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True
APPEND_SLASH = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/
BASE_DIR_MAIN = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR_MAIN, 'static/')


STATICFILES_DIRS = env_mod_setting.STATICFILES_DIRS
print(STATICFILES_DIRS)

# VER_MAJOR = "3"
# VER_MINOR = "7"
# VER_MINOR_MINOR = "1"
VER_MAJOR = os.getenv("VER_MAJOR")
VER_MINOR = os.getenv("VER_MINOR")
VER_MINOR_MINOR = os.getenv("VER_MINOR_MINOR")

APP_VERSION = "{}.{}.{}".format(VER_MAJOR, VER_MINOR, VER_MINOR_MINOR)
print(APP_VERSION)
