"""
Django settings for scikiq project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os



ALLOWED_HOSTS = ['*']

CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS').split(",")
X_FRAME_OPTIONS = '*'
CORS_ALLOW_HEADERS = ['*']
DATA_UPLOAD_MAX_MEMORY_SIZE = os.getenv('DATA_UPLOAD_MAX_MEMORY_SIZE')

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SECRET_KEY = os.getenv('APP_SECRET_KEY')

DEBUG = bool(int(os.getenv('DEBUG')))

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',

    # defined apps
    'apps.retail_all.retail_all_app',
    'apps.logistics_all.logistics_all_app',
    'apps.retail_b2b',
    'apps.retail_b2c',
    'apps.logistics_search',
    'apps.key_data_insight'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.BrokenLinkEmailsMiddleware',
]

CACHE_MIDDLEWARE_SECONDS = 60

ROOT_URLCONF = 'django_setup.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',

            ],
        },
    },
]

WSGI_APPLICATION = 'django_setup.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("POSTGRES_DB"),
        'USER':  os.getenv("POSTGRES_USER"),
        'PASSWORD':  os.getenv("POSTGRES_PASSWORD"),
        'HOST':  os.getenv("POSTGRES_HOST"),
        'PORT':  os.getenv("POSTGRES_PORT"),
        'OPTIONS':
            {
                'options': f'-c search_path={os.getenv("POSTGRES_SCHEMA")}',
            },
    }
}

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True
APPEND_SLASH = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/
BASE_DIR_MAIN = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR_MAIN, 'static/')


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'common', 'web')
]
print(STATICFILES_DIRS)

VER_MAJOR = os.getenv("VER_MAJOR")
VER_MINOR = os.getenv("VER_MINOR")
VER_MINOR_MINOR = os.getenv("VER_MINOR_MINOR")

APP_VERSION = "{}.{}.{}".format(VER_MAJOR, VER_MINOR, VER_MINOR_MINOR)
print(APP_VERSION)
